#!/bin/bash
# Ripped from https://github.com/junegunn/dotfiles/blob/master/install

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
BASE=$(pwd)

# RC Files
for rc in *rc *profile tmux.conf; do
	mkdir -pv bak
	[ -e ~/."$rc" ] && mv -v ~/."$rc" bak/."$rc"
	ln -svf "$BASE/$rc" ~/."$rc"
done

# scripts
mkdir -p ~/bin
for bin in $BASE/bin/*; do
	ln -svf "$bin" ~/bin
done

if [ "$(uname -s)" = 'Darwin' ]; then
	[ -z "$(which brew)" ] &&
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

	echo "Updating brews"
	brew install --cask \
		iterm2 keepingyouawake rectangle \
		karabiner-elements maccy tailscale \
    macfuse openmtp

	brew install \
		fd age ripgrep coreutils zsh git \
		gnupg pass tree vim wget jq python \
		go tmux bat translate-shell oath-toolkit

	brew tap universal-ctags/universal-ctags
	brew install --HEAD universal-ctags
else
	rm -f ~/.tmux.conf
fi

git config --global user.email "daniel@devshell.net"
git config --global user.name "Daniel Lee"
# TODO: Git GPG signing
#git config --global user.signingKey XXXXXXXX
#git config --global commit.gpgsign true

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

./install-vim
